### ISSUE TITLE
'Connect' not working?

### ISSUE THREAD

**Issue by songcarver** [tadija/AEFlowchart#1]
Thanks for making such a cool plugin!
I can't seem to get the Connections working (nothing happens) despite trying to replicate what the video and gif show.

Maybe I'm doing something wrong…

Sketch (Mac App Store) Version 3.0.3 (7891) on 10.9.3

**Comment by ivobenedito** [comment]
Not working for me either :(!

Sketch: Version 3.2.2 (9983)
AEFlowchart: Version: 1.0

**Comment by tadija** [comment]
It's recently updated for version 3.3, so you should use some previous commit for 3.2.2.

**Comment by ivobenedito** [comment]
After updating to Sketch 3.3.1 (12005), it started working. :+1:

**Comment by diogobarm** [comment]
Hi, I am having the same issue.

I am under version 3.4.1 (15681) and recreating the flow on the readme it doesn't connect the states, as shown in the gif below. Also, is there any constrains to have two elements connected, i.e. is there a need to have a start and end element, or a decision box to have two points connected?

Thanks in advance!

![flow](https://cloud.githubusercontent.com/assets/4508654/11034002/e16701ae-86df-11e5-8d83-26a677c2bc7b.gif)

**Comment by tadija** [comment]
Hi, this is fixed now, thanks for reporting.

**Comment by diogobarm** [comment]
Thanks! :+1:
