### ISSUE TITLE
Force closes Sketch when changing shape group size

### ISSUE THREAD

**Issue by sanderfish** [tadija/AEFlowchart#11]
AEFlowchart force closes Sketch when taking the following steps:

1. Create text layer
2. Select text layer 
3. Click 'Process' (Ctrl+Shift+P) or 'Decision' (Ctrl+Shift+D)
4. Select created group
5. Change size by pulling edges

**Comment by tadija** [comment]
Hi, this is now fixed, thanks for reporting!
