### ISSUE TITLE
Not working in Sketch Version 3.8.1?

### ISSUE THREAD

**Issue by aliwright75** [tadija/AEFlowchart#12]
I'm using the trial version of Sketch (v3.8.1) to evaluate it (I believe there's no limitation on functionality). I installed your plugin via Sketch Toolbox, but when I try to turn a piece of text into a 'decision' for example, it doesn't style it accurately. It only uses whatever is set for the font styles in the settings. I also can't seem to connect items either.

**Comment by tadija** [comment]
Hello, thanks for reporting this, it seems that AEFlowchart plugin is broken in latest version, I'll check as soon as I have time for that.

**Comment by aliwright75** [comment]
Thanks for your speedy reply! Thought I was doing something wrong... ;)

**Comment by NorthMcCormick** [comment]
I am also getting this and would love to use this plugin, hope you can check in soon!

**Comment by Bliepjes** [comment]
First and formost, thanks for making this! It looks really usefull and I can't wait for the update

**Comment by dakotayounger** [comment]
Yeah, we're also experiencing the same issue. :(

**Comment by thetylerwolf** [comment]
I have an update to the plugin that works in 3.8+ here:
https://github.com/thetylerwolf/AEFlowchart

Will make a PR

**Comment by tadija** [comment]
Thanks @thetylerwolf, it's merged!
