### ISSUE TITLE
Doesn't work in Sketch Version 48

### ISSUE THREAD

**Issue by verole** [tadija/AEFlowchart#18]
I have been trying to use it in this version (v.48), but every time I select a text layer and select an option in the menu (Start/End, Input/Output.....),  Sketch closes inmediately. 
I have no problems with other plugins.

**Comment by SarahFowler** [comment]
Crashes sketch every time with v48.1 too.

**Comment by tadija** [comment]
Hey @verole and @SarahFowler, thanks for reporting this, I've just released an update with a fix for this.
