### ISSUE TITLE
Input/Output and Decisions - no shape created in Sketch 50

### ISSUE THREAD

**Issue by laurenaldrich** [tadija/AEFlowchart#19]
When I try to apply plugin to text for Input/Output or Decision, no diamond or parallelogram are created. The only thing that happens is the text turns white with a shadow. Not helpful. Maybe incompatible with Sketch 50? 

Thank you!

**Comment by tadija** [comment]
Hi @laurenaldrich, thanks for reporting, I've made a plugin update with a fix for this.

**Comment by laurenaldrich** [comment]
Thank you. It is making the shapes now, but not auto-grouping shape with
text. It's fine, I can group them myself (though a bit of a bother), just
thought you'd like to know.

**Comment by tadija** [comment]
According to my tests in the latest version of Sketch (51.3), it does auto-group shapes with text, so I'll close this issue.
