### ISSUE TITLE
Input/Output, Decision and Connect won't work

### ISSUE THREAD

**Issue by arjavparikh** [tadija/AEFlowchart#20]
These three (Input/Output, Decision and Connect) aren't working as they are demonstrated in the tutorial video. A box isn't being created around them. Only the font style is changed.

**Comment by simonclayson** [comment]
Same for me. Issue seems to have some up in Sketch 52.2. 

If I want to make a connection, the folder AEConnections is created but no layer is created as previous version.

**Comment by tadija** [comment]
Hi, thanks for reporting, this is fixed in the latest update.
