### ISSUE TITLE
Only text changes - no shape created (for all functions) in Sketch 51.3

### ISSUE THREAD

**Issue by frandiam** [tadija/AEFlowchart#21]
When I select text, only the text changes (white with shadow), but there is no corresponding change to the shape or color. Connect doesn't work at all. This is in Sketch version 51.3

**Comment by tadija** [comment]
Hi @frandiam, this plugin is usually updated to support the latest Sketch app version (for example, it works now in 52.4). You could maybe go through commits history and see if there is some older version of the plugin which worked with some specific version of Sketch. For example in your case, I would try with the previous plugin version (2.2.3) which worked in Sketch 50 (which doesn't necessarily mean that it works with 51.3), but after that it was updated to work with Sketch 52.3 and that's the latest plugin version (2.2.4). I hope that helps you!
