### ISSUE TITLE
Feature request: easily customizable style & smart connection

### ISSUE THREAD

**Issue by RYOHOI** [tadija/AEFlowchart#5]
1. Is there an easy way to customize style? I want it to be more "flat". It'll be better if this can be done without touching code. 
2. And I thought if connecting lines can smartly avoid flowchart blocks will be awesome.

thx!~

**Comment by gwenfred** [comment]
i agree too! i prefer to make my own styles.

**Comment by tadija** [comment]
Hi,
1. check out a new version of AEFlowchart in which you can customize the look completely.
2. maybe sometimes in the future... :)
