### ISSUE TITLE
Nothing happens

### ISSUE THREAD

**Issue by ChrisARaymond** [tadija/AEFlowchart#9]
No matter what I do, I select the text, choose anything in the plugin, such as decision, and the Sketch file does nothing in response. Do we need to have only a single Sketch file open? I am on Yosemite, Mac, Sketch 3.4.2, AE Flowchart 2.0.1

**Comment by corygibbons** [comment]
Working for me on Sketch 3.4.2 with AE 2.0.1 (with single or multiple Sketch files open)
Maybe try uninstalling and reinstalling the plugin?

**Comment by tadija** [comment]
Working for me also, did you solve this?

**Comment by tadija** [comment]
Working for me also, did you solve this @ChrisARaymond?

**Comment by tadija** [comment]
New version just had fix for Sketch 3.5 so maybe try that.
